# objective
    The Project contains data of stack-overflow-developers.Data like developers experience,employment status,job     satisfaction,career satisfaction & Salary etc.
    project's objective is to predict whether a person will opt to contribute for an open source projet or not.
  

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/stack-overflow-2018-developer-survey/survey_results_public.csv
/kaggle/input/stack-overflow-2018-developer-survey/survey_results_schema.csv


 # Importing libraries
     Numpy and panda libraries has a lot of predefined functions that will be essential 
     for us in project
****

In [2]:
import numpy as np
import pandas as pd

1. # Importing Dataframe
Here we are importing datasets in to our notebook from Kaggle data sets repository  

In [3]:
dataset=pd.read_csv('/kaggle/input/stack-overflow-2018-developer-survey/survey_results_public.csv')
dataset2=pd.read_csv('/kaggle/input/stack-overflow-2018-developer-survey/survey_results_schema.csv')

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (8,12,13,14,15,16,50,51,52,53,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


# Assigning first 17 columns of dataframe to a new data frame mydata

In [4]:
mydata=dataset.iloc[:,:17]

In [5]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98855 entries, 0 to 98854
Data columns (total 17 columns):
Respondent            98855 non-null int64
Hobby                 98855 non-null object
OpenSource            98855 non-null object
Country               98443 non-null object
Student               94901 non-null object
Employment            95321 non-null object
FormalEducation       94703 non-null object
UndergradMajor        79036 non-null object
CompanySize           71531 non-null object
DevType               92098 non-null object
YearsCoding           93835 non-null object
YearsCodingProf       77903 non-null object
JobSatisfaction       69276 non-null object
CareerSatisfaction    76504 non-null object
HopeFiveYears         75718 non-null object
JobSearchStatus       79488 non-null object
LastNewJob            78889 non-null object
dtypes: int64(1), object(16)
memory usage: 12.8+ MB


#  As we can see our data has some null values
# Below steps are to drop rows containing null values

In [6]:
mydata = mydata.dropna(axis=0, subset=['JobSatisfaction'])

In [7]:
mydata = mydata.dropna(axis=0, subset=['Country'])

In [8]:
mydata = mydata.dropna(axis=0, subset=['Student'])

In [9]:
mydata = mydata.dropna(axis=0, subset=['Employment'])

In [10]:
mydata = mydata.dropna(axis=0, subset=['FormalEducation'])

In [11]:
mydata = mydata.dropna(axis=0, subset=['UndergradMajor'])

In [12]:
mydata = mydata.dropna(axis=0, subset=['CompanySize'])

In [13]:
mydata = mydata.dropna(axis=0, subset=['DevType'])

In [14]:
mydata = mydata.dropna(axis=0, subset=['YearsCoding'])

In [15]:
mydata = mydata.dropna(axis=0, subset=['YearsCodingProf'])

In [16]:
mydata = mydata.dropna(axis=0, subset=['CareerSatisfaction'])

In [17]:
mydata = mydata.dropna(axis=0, subset=['HopeFiveYears'])

In [18]:
mydata = mydata.dropna(axis=0, subset=['JobSearchStatus'])

In [19]:
mydata = mydata.dropna(axis=0, subset=['LastNewJob'])

In [20]:
mydata = mydata.dropna(axis=0, subset=['OpenSource'])

  # Let us chechk if there are more null values

In [21]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53050 entries, 0 to 71530
Data columns (total 17 columns):
Respondent            53050 non-null int64
Hobby                 53050 non-null object
OpenSource            53050 non-null object
Country               53050 non-null object
Student               53050 non-null object
Employment            53050 non-null object
FormalEducation       53050 non-null object
UndergradMajor        53050 non-null object
CompanySize           53050 non-null object
DevType               53050 non-null object
YearsCoding           53050 non-null object
YearsCodingProf       53050 non-null object
JobSatisfaction       53050 non-null object
CareerSatisfaction    53050 non-null object
HopeFiveYears         53050 non-null object
JobSearchStatus       53050 non-null object
LastNewJob            53050 non-null object
dtypes: int64(1), object(16)
memory usage: 7.3+ MB


In [22]:
mydata.isnull().sum()

Respondent            0
Hobby                 0
OpenSource            0
Country               0
Student               0
Employment            0
FormalEducation       0
UndergradMajor        0
CompanySize           0
DevType               0
YearsCoding           0
YearsCodingProf       0
JobSatisfaction       0
CareerSatisfaction    0
HopeFiveYears         0
JobSearchStatus       0
LastNewJob            0
dtype: int64

# Now, we can see that thre are no more null values in dataframe

# creating X with all independent variables and y with all dependent variables

As I mentioned before, Our objective is to predict 'Yes' or 'No' for open source.
So, y variable is Open_Source.

In [23]:
y=pd.DataFrame(mydata.iloc[:,2])

df=pd.DataFrame(mydata)
X=df.drop(['OpenSource'],axis=1)


# dummification
 Machine cannot understand Strings(Categorical Variables).So, a number should be assigned to every Strings(Catgorical Variable),Whenever this number occurs in that column, machine understands that respective String categorical variable has occured.This process of converting  Strings(categorical variables) in to numerical factors is called dummification.
 
 Below given steps are of dummification of X and y dataframes. 

In [24]:
a=pd.get_dummies(X,drop_first=True)

In [25]:
b=pd.get_dummies(y, drop_first=True)

# splitting data in to train and test sets
We split the data set in to test and train data sets.We perform our model on train data set and test our model on test data set.

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,y_train,y_test=train_test_split(a,b,test_size=0.2,random_state=0)

* # Applying decision tree classifier on train dataset

In [28]:
from sklearn.tree import DecisionTreeClassifier
regression=DecisionTreeClassifier()
regression.fit(X_train,y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

# performing prediction for test dataset
  In next steps we perform prediction on Open_source for test data set and compare it with the actual Data.

In [29]:
y_pred=regression.predict(X_test)

In [30]:
y_pred

array([0, 0, 1, ..., 0, 1, 0], dtype=uint8)

# Calculating accuracy of our prediction
In next steps we calcuate accuracy,Here accuracy is (no of correct predictions)/total no of observations.More the accuracy,better our model is.

In [31]:
from sklearn.metrics import confusion_matrix

In [32]:
cm=confusion_matrix(y_test,y_pred)

In [33]:
cm

array([[3825, 2269],
       [2322, 2194]])

In [34]:
total=sum(sum(cm))

In [35]:
accuracy=(cm[0,0]+cm[1,1])/total

In [36]:
accuracy

0.5672950047125354

We got an accuracy of 56.3 percent i.e of all the predicted outputs, 56.3 are correct

So, let us try random forest model and check the accuracy

# Performing Randomforestclassificaton on train dataset
Below, we perform the same steps above but we are doing it for Random forest model.

In [37]:
from sklearn.ensemble import RandomForestClassifier
randomclassifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
randomclassifier.fit(X_train,y_train)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [38]:
y_pred2=randomclassifier.predict(X_test)

# Calculating accuracy of prediction

In [39]:
cm2=confusion_matrix(y_test,y_pred2)

In [40]:
cm2

array([[4753, 1341],
       [3046, 1470]])

In [41]:
total2=sum(sum(cm2))

In [42]:
accuracy2=(cm2[0,0]+cm2[1,1])/total2

In [43]:
accuracy2

0.5865221489161169

Random forest model is giving us more accuracy(58.6%) than decision tree model(56.2%), but still this is not good enough.

We can  make this model more accurate by removing the indpendent variables which does not gave much impact on depndent variable.


In next steps, We are trying to remove those columns which doesnot have much impact on our 
dependent variable(Open_Source). This helps in increasing accuracy of our prediction

We are trying to check whether 'Country' and 'DevType' columns are significant or not because the no of distinct observtions in these two columns are far more when compared to other columns and if they are not affecting independent variables then we could get rid of thse two columns.


In [44]:
m=[]
z=0
for i in range(187,5977):
    k=X_train.columns[i]
    for j in range(0,42440):
     if(X_train[k].values[j]==1):
        
       if(y_train.iloc[j][0]==1):
            m.append(True)
       else:
            m.append(False)
            
            
    if(all(m)==any(m)):
        print(i)
        z=z+1
            
    
        
    
          



In [45]:
m=[]
z=0
for i in range(2,161):
    k=X_train.columns[i]
    for j in range(0,42440):
     if(X_train[k].values[j]==1):
        
       if(y_train.iloc[j][0]==1):
            m.append(True)
       else:
            m.append(False)
            
            
    if(all(m)==any(m)):
        print(i)
        z=z+1

After checking whether obsevations in "DevType' and 'Country' are showing any impact on our dependent variable.
we found out that both of these colums are not showing any impact on our dependent variable

In next steps, we remove all the dummy columns of dependent variables 'DevType' 
and 'Country' from train data set and test dataset

In [46]:
X_train.drop(X_train.iloc[:,2:160],inplace=True,axis=1)

/opt/conda/lib/python3.6/site-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [47]:
X_train.drop(X_train.iloc[:,187:5976],inplace=True,axis=1)

In [48]:
X_test.drop(X_test.iloc[:,2:160],inplace=True,axis=1)

In [49]:
X_test.drop(X_test.iloc[:,187:5976],inplace=True,axis=1)

In next steps we reiteerate the steps that we performed while calculating accuracy for decision tree model and Random foreest model.Only difference is we are prforming it on updated datasets, i.e dataset after removing columns 'DevType' and 'Country'.

In [50]:
from sklearn.tree import DecisionTreeClassifier
classification=DecisionTreeClassifier()
classification.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [51]:
y3_pred=classification.predict(X_test)

In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
cm3=confusion_matrix(y_test,y3_pred)

In [54]:
accuracy3=(cm3[0,0]+cm3[1,1])/sum(sum(cm3))

In [55]:
accuracy3

0.5317624882186617

Accuracy we got for updated dataset is 52.9 which is less when compared to  56.2 i.e accuracy we got with first dataset

Now, let us check Random forest on updated dataset

In [56]:
from sklearn.ensemble import RandomForestClassifier
randomclassifier2=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
randomclassifier2.fit(X_train,y_train)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [57]:
y_pred4=randomclassifier2.predict(X_test)

In [58]:
cm4=confusion_matrix(y_test,y_pred4)

In [59]:
accuracy4=(cm4[0,0]+cm4[1,1])/sum(sum(cm4))

In [60]:
accuracy4

0.5397737983034873

Accuracy of Random forest model on updated data set is 53.9 which is less than 58.6,i.e accuracy of Random forest model on first data set.

As Accuracy of Random forest model on first data set is more.We Should predict our independent variable by performing Random forest model on first data set.